/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.tela;

import br.com.senai.entidade.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author SESI_SENAI
 */
public class Principal extends javax.swing.JFrame {

    private Usuario usuario;
    
    public Principal(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linkCadUsuario = new javax.swing.JLabel();
        linkPesqUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastro = new javax.swing.JMenu();
        menuItemCadUsuario = new javax.swing.JMenuItem();
        menuItemCadProfissao = new javax.swing.JMenuItem();
        menu_pesquisa = new javax.swing.JMenu();
        menuItemPesqUsuario = new javax.swing.JMenuItem();
        menuItemPesquisaProfissao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Senai");

        linkCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/adicionar-usuario _64.png"))); // NOI18N
        linkCadUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        linkCadUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkCadUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkCadUsuarioMouseClicked(evt);
            }
        });

        linkPesqUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pesquisar-usuario.png"))); // NOI18N
        linkPesqUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        linkPesqUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkPesqUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkPesqUsuarioMouseClicked(evt);
            }
        });

        menu_cadastro.setText("Cadastro");

        menuItemCadUsuario.setText("Usuário");
        menuItemCadUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemCadUsuarioMousePressed(evt);
            }
        });
        menu_cadastro.add(menuItemCadUsuario);

        menuItemCadProfissao.setText("Profissão");
        menu_cadastro.add(menuItemCadProfissao);

        jMenuBar1.add(menu_cadastro);

        menu_pesquisa.setText("Pesquisa");

        menuItemPesqUsuario.setText("Usuario");
        menuItemPesqUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemPesqUsuarioMousePressed(evt);
            }
        });
        menu_pesquisa.add(menuItemPesqUsuario);

        menuItemPesquisaProfissao.setText("Profissao");
        menu_pesquisa.add(menuItemPesquisaProfissao);

        jMenuBar1.add(menu_pesquisa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(linkCadUsuario)
                .addGap(26, 26, 26)
                .addComponent(linkPesqUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(linkPesqUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linkCadUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCadUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemCadUsuarioMousePressed
        new CadastroUsuario().setVisible(true);
    }//GEN-LAST:event_menuItemCadUsuarioMousePressed

    private void linkCadUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkCadUsuarioMouseClicked
        new CadastroUsuario().setVisible(true);
    }//GEN-LAST:event_linkCadUsuarioMouseClicked

    private void menuItemPesqUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemPesqUsuarioMousePressed
        new PesquisaUsuario().setVisible(true);
    }//GEN-LAST:event_menuItemPesqUsuarioMousePressed

    private void linkPesqUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkPesqUsuarioMouseClicked
        new PesquisaUsuario().setVisible(true);
    }//GEN-LAST:event_linkPesqUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel linkCadUsuario;
    private javax.swing.JLabel linkPesqUsuario;
    private javax.swing.JMenuItem menuItemCadProfissao;
    private javax.swing.JMenuItem menuItemCadUsuario;
    private javax.swing.JMenuItem menuItemPesqUsuario;
    private javax.swing.JMenuItem menuItemPesquisaProfissao;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenu menu_pesquisa;
    // End of variables declaration//GEN-END:variables
}
